package com.model;

/**
 * TBianmindianhua generated by MyEclipse Persistence Tools
 */

public class TBianmindianhua implements java.io.Serializable
{

	// Fields

	private Integer id;

	private String name;

	private String dianhua;

	private String del;

	// Constructors

	/** default constructor */
	public TBianmindianhua()
	{
	}

	/** full constructor */
	public TBianmindianhua(String name, String dianhua, String del)
	{
		this.name = name;
		this.dianhua = dianhua;
		this.del = del;
	}

	// Property accessors

	public Integer getId()
	{
		return this.id;
	}

	public void setId(Integer id)
	{
		this.id = id;
	}

	public String getName()
	{
		return this.name;
	}

	public void setName(String name)
	{
		this.name = name;
	}

	public String getDianhua()
	{
		return this.dianhua;
	}

	public void setDianhua(String dianhua)
	{
		this.dianhua = dianhua;
	}

	public String getDel()
	{
		return this.del;
	}

	public void setDel(String del)
	{
		this.del = del;
	}

}