package com.model;

/**
 * TBiaogexiazai generated by MyEclipse Persistence Tools
 */

public class TBiaogexiazai implements java.io.Serializable
{

	// Fields

	private Integer id;

	private String name;

	private String jieshao;

	private String fujian;

	private String fujianYuanshiming;

	private String shangchuanshijian;

	private String del;

	// Constructors

	/** default constructor */
	public TBiaogexiazai()
	{
	}

	/** full constructor */
	public TBiaogexiazai(String name, String jieshao, String fujian,
			String fujianYuanshiming, String shangchuanshijian, String del)
	{
		this.name = name;
		this.jieshao = jieshao;
		this.fujian = fujian;
		this.fujianYuanshiming = fujianYuanshiming;
		this.shangchuanshijian = shangchuanshijian;
		this.del = del;
	}

	// Property accessors

	public Integer getId()
	{
		return this.id;
	}

	public void setId(Integer id)
	{
		this.id = id;
	}

	public String getName()
	{
		return this.name;
	}

	public void setName(String name)
	{
		this.name = name;
	}

	public String getJieshao()
	{
		return this.jieshao;
	}

	public void setJieshao(String jieshao)
	{
		this.jieshao = jieshao;
	}

	public String getFujian()
	{
		return this.fujian;
	}

	public void setFujian(String fujian)
	{
		this.fujian = fujian;
	}

	public String getFujianYuanshiming()
	{
		return this.fujianYuanshiming;
	}

	public void setFujianYuanshiming(String fujianYuanshiming)
	{
		this.fujianYuanshiming = fujianYuanshiming;
	}

	public String getShangchuanshijian()
	{
		return this.shangchuanshijian;
	}

	public void setShangchuanshijian(String shangchuanshijian)
	{
		this.shangchuanshijian = shangchuanshijian;
	}

	public String getDel()
	{
		return this.del;
	}

	public void setDel(String del)
	{
		this.del = del;
	}

}