package com.model;

import java.util.Date;

/**
 * TPicNews generated by MyEclipse Persistence Tools
 */

public class TPicNews implements java.io.Serializable
{

	// Fields

	private Integer picNewsId;

	private String picNewsTitle;

	private String picNewsContent;
	
	private String fujian;
	
	private String fujianYuanshiming;

	private String picNewsDate;

	private String picNewsOne1;

	private String picNewsOne2;

	private String picNewsOne3;

	private String picNewsOne4;

	private Date picNewsOne5;

	private Date picNewsOne6;

	private Integer picNewsOne7;

	private Integer picNewsOne8;

	// Constructors

	/** default constructor */
	public TPicNews()
	{
	}

	/** full constructor */
	public TPicNews(String picNewsTitle, String picNewsContent,
			String picNewsDate, String picNewsOne1, String picNewsOne2,
			String picNewsOne3, String picNewsOne4, Date picNewsOne5,
			Date picNewsOne6, Integer picNewsOne7, Integer picNewsOne8)
	{
		this.picNewsTitle = picNewsTitle;
		this.picNewsContent = picNewsContent;
		this.picNewsDate = picNewsDate;
		this.picNewsOne1 = picNewsOne1;
		this.picNewsOne2 = picNewsOne2;
		this.picNewsOne3 = picNewsOne3;
		this.picNewsOne4 = picNewsOne4;
		this.picNewsOne5 = picNewsOne5;
		this.picNewsOne6 = picNewsOne6;
		this.picNewsOne7 = picNewsOne7;
		this.picNewsOne8 = picNewsOne8;
	}

	// Property accessors

	public Integer getPicNewsId()
	{
		return this.picNewsId;
	}

	public void setPicNewsId(Integer picNewsId)
	{
		this.picNewsId = picNewsId;
	}

	public String getPicNewsTitle()
	{
		return this.picNewsTitle;
	}

	public void setPicNewsTitle(String picNewsTitle)
	{
		this.picNewsTitle = picNewsTitle;
	}


	public String getFujian()
	{
		return fujian;
	}

	public void setFujian(String fujian)
	{
		this.fujian = fujian;
	}

	public String getFujianYuanshiming()
	{
		return fujianYuanshiming;
	}

	public void setFujianYuanshiming(String fujianYuanshiming)
	{
		this.fujianYuanshiming = fujianYuanshiming;
	}

	public String getPicNewsContent()
	{
		return this.picNewsContent;
	}

	public void setPicNewsContent(String picNewsContent)
	{
		this.picNewsContent = picNewsContent;
	}

	public String getPicNewsDate()
	{
		return this.picNewsDate;
	}

	public void setPicNewsDate(String picNewsDate)
	{
		this.picNewsDate = picNewsDate;
	}

	public String getPicNewsOne1()
	{
		return this.picNewsOne1;
	}

	public void setPicNewsOne1(String picNewsOne1)
	{
		this.picNewsOne1 = picNewsOne1;
	}

	public String getPicNewsOne2()
	{
		return this.picNewsOne2;
	}

	public void setPicNewsOne2(String picNewsOne2)
	{
		this.picNewsOne2 = picNewsOne2;
	}

	public String getPicNewsOne3()
	{
		return this.picNewsOne3;
	}

	public void setPicNewsOne3(String picNewsOne3)
	{
		this.picNewsOne3 = picNewsOne3;
	}

	public String getPicNewsOne4()
	{
		return this.picNewsOne4;
	}

	public void setPicNewsOne4(String picNewsOne4)
	{
		this.picNewsOne4 = picNewsOne4;
	}

	public Date getPicNewsOne5()
	{
		return this.picNewsOne5;
	}

	public void setPicNewsOne5(Date picNewsOne5)
	{
		this.picNewsOne5 = picNewsOne5;
	}

	public Date getPicNewsOne6()
	{
		return this.picNewsOne6;
	}

	public void setPicNewsOne6(Date picNewsOne6)
	{
		this.picNewsOne6 = picNewsOne6;
	}

	public Integer getPicNewsOne7()
	{
		return this.picNewsOne7;
	}

	public void setPicNewsOne7(Integer picNewsOne7)
	{
		this.picNewsOne7 = picNewsOne7;
	}

	public Integer getPicNewsOne8()
	{
		return this.picNewsOne8;
	}

	public void setPicNewsOne8(Integer picNewsOne8)
	{
		this.picNewsOne8 = picNewsOne8;
	}

}