package com.model;

/**
 * TZhengwu generated by MyEclipse Persistence Tools
 */

public class TZhengwu implements java.io.Serializable
{

	// Fields

	private Integer id;

	private String title;

	private String content;

	private String shijian;

	private String del;

	// Constructors

	/** default constructor */
	public TZhengwu()
	{
	}

	/** full constructor */
	public TZhengwu(String title, String content, String shijian, String del)
	{
		this.title = title;
		this.content = content;
		this.shijian = shijian;
		this.del = del;
	}

	// Property accessors

	public Integer getId()
	{
		return this.id;
	}

	public void setId(Integer id)
	{
		this.id = id;
	}

	public String getTitle()
	{
		return this.title;
	}

	public void setTitle(String title)
	{
		this.title = title;
	}

	public String getContent()
	{
		return this.content;
	}

	public void setContent(String content)
	{
		this.content = content;
	}

	public String getShijian()
	{
		return this.shijian;
	}

	public void setShijian(String shijian)
	{
		this.shijian = shijian;
	}

	public String getDel()
	{
		return this.del;
	}

	public void setDel(String del)
	{
		this.del = del;
	}

}